site_name: "Moe's Site"
site_url: https://shocked-pikachu.github.io/moe.site/

# Repository
repo_name: Shocked-Pikachu/moe.site
repo_url: https://github.com/Shocked-Pikachu/moe.site

copyright: |
  &copy; 2024 - 2025 <a href="https://github.com/Shocked-Pikachu" target="_blank" rel="noopener"> Haoyu Mo</a>

theme:
  name: material
  custom_dir: docs/overrides

  language: zh

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    # - navigation.sections
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font: false

  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra:
  social:
    - icon: fontawesome/brands/github
      name: My Github
      link: https://github.com/Shocked-Pikachu
    - icon: /fontawesome/regular/envelope
      name: Send Me An Email
      link: mailto:<mohy@stu.pku.edu.cn>

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang:
        - en
        - zh
      separator: '[\s\-\.]+' # split words by space, dash, or dot

  
  - git-revision-date-localized:
        enable_creation_date: true
        type: date
        exclude:
        - index.md
        timezone: Asia/Shanghai
        locale: zh
  

nav:
  - 主页: index.md
  - 课程:
    - courses/index.md
    - 电动力学:
        - courses/electrodynamics/index.md
    - 现代主义音乐：挑战与挑衅:
        - courses/musical-modernism/index.md
    - 近代物理实验:
        - courses/modern-physics-lab/index.md
    - 经济学原理（I）:
        - courses/principles-of-economics/index.md
        - 经济学基本原理: courses/principles-of-economics/principles-economics.md
        - 双赢的贸易: courses/principles-of-economics/gains-from-trade.md
        - 供需的市场力量: courses/principles-of-economics/market-forces-supply-demand.md
        - 弹性及其应用: courses/principles-of-economics/elasticity-application.md
        - 市场与政策: courses/principles-of-economics/markets-government-policies.md
        - 市场效率: courses/principles-of-economics/market-efficiency.md
        - 外部性及公共品: courses/principles-of-economics/externality-public-goods.md
        - 消费者理论: courses/principles-of-economics/consumer-theory.md
        - 厂商理论: courses/principles-of-economics/producer-theory.md
        - 竞争市场中的企业: courses/principles-of-economics/firms-competitive-markets.md
        - 垄断: courses/principles-of-economics/monopoly.md
        - 垄断竞争及生产要素市场: courses/principles-of-economics/monopolistic-competition-markets-factors-production.md
        - 寡头与博弈论: courses/principles-of-economics/oligopoly-game-theory.md
        - 杂及前沿: courses/principles-of-economics/miscellany-frontiers.md
    - 金融学概论:
        - courses/introduction-to-finance/index.md
        - Introduction: courses/introduction-to-finance/introduction.md
        - Allocating Resources Over Time: courses/introduction-to-finance/time-value-money.md
        - Asset Classes: courses/introduction-to-finance/asset-classes.md
        - Trading, Margin and Short Sale: courses/introduction-to-finance/trading-margin-short-sale.md
        - Stock Market Indexes & Funds: courses/introduction-to-finance/stock-market-indexes-funds.md
        - Historical Returns on Risky Portfolios: courses/introduction-to-finance/historical-returns.md
        - Introduction to Portfolio Choice: courses/introduction-to-finance/introduction-portfolio-choice.md
        - Constructing Portfolios: courses/introduction-to-finance/constructing-portfolios.md
        - Optimal Risky Portfolios: courses/introduction-to-finance/optimal-risky-portfolios.md
        - Markowitz Portfolio Selection Model: courses/introduction-to-finance/markowitz-portfolio-selection-model.md
        - Index Models: courses/introduction-to-finance/index-models.md
        - Capital Asset Pricing Model: courses/introduction-to-finance/capital-asset-pricing-model.md
        - Arbitrage Pricing Theory: courses/introduction-to-finance/arbitrage-pricing-theory.md
        - Bond Prices and Yields: courses/introduction-to-finance/bond-prices-yields.md
        - The Term Structure of Interest Rates: courses/introduction-to-finance/term-structure-interest-rates.md
        - Equity Valuation: courses/introduction-to-finance/equity-valuation.md
        - Option Strategies and Put-Call Parity: courses/introduction-to-finance/option-strategies-put-call-parity.md
        - Option Pricing: courses/introduction-to-finance/option-pricing.md
        - Futures: courses/introduction-to-finance/futures.md
        - Structured Finance: courses/introduction-to-finance/structured-finance.md
        - Financial Fragility: courses/introduction-to-finance/financial-fragility.md
    - 财务会计:
        - courses/financial-accounting/index.md
        - Lecture 1: courses/financial-accounting/lecture-1.md
        - Lecture 2: courses/financial-accounting/lecture-2.md
        - Lecture 3: courses/financial-accounting/lecture-3.md
        - Lecture 4: courses/financial-accounting/lecture-4.md
        - Lecture 5: courses/financial-accounting/lecture-5.md
        - Lecture 6: courses/financial-accounting/lecture-6.md
        - Lecture 7: courses/financial-accounting/lecture-7.md
        - Lecture 8: courses/financial-accounting/lecture-8.md
        - Lecture 9: courses/financial-accounting/lecture-9.md
        - Lecture 10: courses/financial-accounting/lecture-10.md
        - Lecture 11: courses/financial-accounting/lecture-11.md
        - Lecture 12: courses/financial-accounting/lecture-12.md
        - Lecture 13: courses/financial-accounting/lecture-13.md
        - Lecture 14: courses/financial-accounting/lecture-14.md
    - 量化金融专题:
        - courses/topics-quantitative-finance/index.md
        - Lecture 1 Financial Engineering in a Nutshell: courses/topics-quantitative-finance/financial-engineering-nutshell.md
        - Lecture 2 Crash Course on Stochastic Calculus: courses/topics-quantitative-finance/stochastic-calculus.md
        - Lecture 3 The Black-Merton-Scholes Model and Beyond I: courses/topics-quantitative-finance/black-scholes-1.md
        - Lecture 4 The Black-Merton-Scholes Model and Beyond II: courses/topics-quantitative-finance/black-scholes-2.md
        - Lecture 5 Volatility and Volatility-Linked Derivatives: courses/topics-quantitative-finance/volatility.md
        - Lecture 6 Brief Introduction to Variational and Control Problems: courses/topics-quantitative-finance/variational-control-problems.md
        - Lecture 7 Optimal Execution under Price Impact: courses/topics-quantitative-finance/optimal-execution.md
    - 广义相对论:
        - courses/general-relativity/index.md
    - 人工智能基础:
        - courses/ai-basis/index.md
    - 产业组织理论:
        - courses/industrial-organization-theory/index.md
        - 产业组织简介，完全竞争: courses/industrial-organization-theory/introduction-comp.md
        - 垄断: courses/industrial-organization-theory/monopoly.md
        - 寡头: courses/industrial-organization-theory/oligopoly.md
        - 垄断竞争: courses/industrial-organization-theory/monocom.md
        - 非线性定价与区别定价: courses/industrial-organization-theory/price-discrimination.md
        - 捆绑销售: courses/industrial-organization-theory/tie-in-sale.md
        - 策略行为: courses/industrial-organization-theory/strategic-behavior.md
        - 耐用品: courses/industrial-organization-theory/durables.md
        - 广告与信息: courses/industrial-organization-theory/information.md
        - 研究与开发: courses/industrial-organization-theory/research-development.md
        - 水平合并: courses/industrial-organization-theory/horizontal.md
        - 垂直合并: courses/industrial-organization-theory/vertical.md
        - 国际贸易: courses/industrial-organization-theory/international-trade.md
    - 17 与 18 世纪的欧洲艺术音乐：巴洛克与古典风格:
        - courses/baroque-classical-style-music/index.md
        - “巴洛克”？从⽂艺复兴末期出发: courses/baroque-classical-style-music/end-renaissance-concept-baroque.md
        - 歌剧的诞⽣：“从蒙特威尔第的牧歌到蒙特威尔第的歌剧”: courses/baroque-classical-style-music/monteverdi-madrigals-operas.md
        - 法国抒情悲剧中的权⼒与愉悦：从吕利到拉莫: courses/baroque-classical-style-music/spectacle-power-pleasure.md
        - 法国、意⼤利与北德的键盘音乐：L. 库普兰、弗雷斯科巴尔蒂、扬·皮泰尔索恩·斯韦林克、F. 库普兰、布克斯特胡德: courses/baroque-classical-style-music/baroque-keyboard-tradition.md
        - 意⼤利协奏曲风格与调性的兴起：科雷利与维瓦尔第: courses/baroque-classical-style-music/italian-concerto-style.md
        - 亨德尔的意⼤利歌剧、英国神剧与器乐作品: courses/baroque-classical-style-music/handel.md
        - 巴赫的键盘音乐：键盘十二平均律、哥德堡变奏曲: courses/baroque-classical-style-music/introduction-bach.md
        - 巴赫的协奏曲与组曲: courses/baroque-classical-style-music/bach-dance-suite-concertos.md
        - 巴赫的声乐作品：康塔塔与受难曲: courses/baroque-classical-style-music/bach-cantatas-passions.md
        - 喜歌剧的兴起：佩格莱西与歌剧中的⼆维性格: courses/baroque-classical-style-music/early-classical-styles.md
        - 奏鸣曲式：鍵盤奏鸣曲、早期交响乐与协奏曲: courses/baroque-classical-style-music/emergence-comic-operas.md
        - 莫扎特的喜歌剧：启蒙主义精神的体现: courses/baroque-classical-style-music/enlightenment-mozart-operas.md
        - 有幽默感的海顿：弦乐四重奏与交响乐: courses/baroque-classical-style-music/haydn.md
    - 财务报表分析:
        - courses/financial-statement-analysis/index.md
        - Lecture 1: courses/financial-statement-analysis/lecture-1.md
        - Lecture 2: courses/financial-statement-analysis/lecture-2.md
        - Lecture 3: courses/financial-statement-analysis/lecture-3.md
        - Lecture 4: courses/financial-statement-analysis/lecture-4.md
        - Lecture 5: courses/financial-statement-analysis/lecture-5.md
        - Lecture 6: courses/financial-statement-analysis/lecture-6.md
        - Lecture 7: courses/financial-statement-analysis/lecture-7.md
        - Lecture 8: courses/financial-statement-analysis/lecture-8.md
        - Lecture 9: courses/financial-statement-analysis/lecture-9.md
        - Lecture 10: courses/financial-statement-analysis/lecture-10.md
        - Lecture 11: courses/financial-statement-analysis/lecture-11.md
        - Lecture 12: courses/financial-statement-analysis/lecture-12.md
  - 关于: about/index.md